
version: "3"

volumes:
  laravel-auth-database_data:
    driver: local

services:

  laravel-app:
    container_name: laravel-app
    image: webdevops/php-nginx-dev:8.2
    platform: linux/amd64
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    ports:
      - "8000:80"
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
    depends_on:
      - laravel-database

  laravel-database:
    container_name: laravel-database
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - laravel-auth-database_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel


    

    


