
version: "3"

volumes:
  laravel-auth-database_data:
    driver: local

services:
  laravel-auth-app:
    platform: linux/amd64
    container_name: ${APP_PHP_SERVICE}
    image: webdevops/php-nginx-dev:7.3
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    ports:
      - "${APP_PHP_PORT}:80"
    depends_on:
      - laravel-auth-database

  laravel-auth-database:
    container_name: ${APP_MYSQL_SERVICE}
    image: mariadb:10.6
    volumes:
      - laravel-auth-database_data:/var/lib/mysql
    ports:
      - "${APP_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

